// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio_Inventario.Modelos;

public partial class EstadosProductos
{
    public int IdEstadoProducto { get; set; }

    public string NombreEstado { get; set; }

    public string DescripcionEstado { get; set; }

    public virtual ICollection<Productos> Productos { get; set; } = new List<Productos>();
}