// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio_Inventario.Modelos;

public partial class EstadosLotes
{
    public int IdEstadoLote { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<LotesProductos> LotesProductos { get; set; } = new List<LotesProductos>();
}