// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio_Inventario.Modelos;

public partial class Productos
{
    public int IdProducto { get; set; }

    public int IdEstadoProducto { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string Imagen { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public int IdUsuarioCreacion { get; set; }

    public int? IdUsuarioActualizacion { get; set; }

    public virtual EstadosProductos IdEstadoProductoNavigation { get; set; }

    public virtual ICollection<LotesProductos> LotesProductos { get; set; } = new List<LotesProductos>();
}